pipeline {
    agent any

    environment {
        //REGISTRY_USER     = 'vercetti06'
        //IMAGE_NAME        = 'api-leave'
        //DOCKER_HUB        = credentials('docker-hub-credentials')
        AWS_ACCOUNT_ID   = credentials('aws-account-id')
        AWS_REGION       = 'us-east-1'
        ECR_REPO         = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/leave-api"

        SONAR_PROJECT_KEY = 'Vercetti06_Sample-Leave-API'
        SONAR_ORG_KEY     = 'ercetti06'

        TARGET_FILE       = 'Sample-app-dev/kubernetes-manifests/app/app-deployment.yml'

        GIT_REPO_NAME = "Sample-Leave-API"
        GIT_USER_NAME = "Vercetti06"
    }

    stages {
        stage('Checkout') {
    steps {
        deleteDir()
        checkout([
            $class: 'GitSCM',
            branches: [[name: '*/main']],
            doGenerateSubmoduleConfigurations: false,
            extensions: [[$class: 'CleanBeforeCheckout']],
            userRemoteConfigs: [[
                url: "https://github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git",
                credentialsId: 'github-creds'
            ]]
        ])
    }
}

        stage('Build Docker Image') {
            steps {
               // sh "docker build -t ${REGISTRY_USER}/${IMAGE_NAME}:${BUILD_NUMBER} Sample-app-dev/"
            sh "docker build -t ${ECR_REPO}:${BUILD_NUMBER} Sample-app-dev/"
            }
        }

        stage('SonarQube Cloud SAST') {
            steps {
                withSonarQubeEnv('SonarQubeCloud') {
                    script {
                        def scannerHome = tool 'SonarScanner'
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                              -Dsonar.organization=${SONAR_ORG_KEY} \
                              -Dsonar.sources=Sample-app-dev/ \
                              -Dsonar.inclusions=**/*.py,**/requirements.txt \
                              -Dsonar.qualitygate.wait=true
                        """
                    }
                }
            }
        }

        stage('Trivy FS Scan') {
    steps {
        sh 'trivy fs --exit-code 0 --severity HIGH,CRITICAL Sample-app-dev/main.py'
        sh 'trivy fs --exit-code 0 --severity HIGH,CRITICAL Sample-app-dev/requirements.txt'
    }
}

        stage('Unit & Health Test') {
            steps {
                sh '''
                    echo "Starting test container..."
                    #docker run -d --name test-container -p 8001:8000 ${REGISTRY_USER}/${IMAGE_NAME}:${BUILD_NUMBER}
                    docker run -d --name test-container -p 8001:8000 ${ECR_REPO}:${BUILD_NUMBER}

                    echo "Giving application lifecycle initialization room..."
                    sleep 5

                    echo "Verifying service endpoints..."
                    curl -f http://localhost:8001/health

                    echo "Tearing down runtime resources..."
                    docker stop test-container
                    docker rm test-container
                '''
            }
        }

        stage('Trivy Image Scan') {
            steps {
                //sh "trivy image --exit-code 0 --severity HIGH,CRITICAL ${REGISTRY_USER}/${IMAGE_NAME}:${BUILD_NUMBER}"
                sh "trivy image --exit-code 0 --severity HIGH,CRITICAL ${ECR_REPO}:${BUILD_NUMBER}"
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh '''
                    #echo "$DOCKER_HUB_PSW" | docker login -u "$DOCKER_HUB_USR" --password-stdin
                    #docker push ${REGISTRY_USER}/${IMAGE_NAME}:${BUILD_NUMBER}

                    aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
                    docker push $ECR_REPO:${BUILD_NUMBER}
                '''
            }
        }

        stage('Update Manifest & Push Changes') {
    steps {
        withCredentials([usernamePassword(
            credentialsId: 'github-creds',
            usernameVariable: 'GIT_USER',
            passwordVariable: 'GIT_TOKEN'
        )]) {
            sh '''
                #sed -i "s|image: ${REGISTRY_USER}/${IMAGE_NAME}:.*|image: ${REGISTRY_USER}/${IMAGE_NAME}:${BUILD_NUMBER}|" ${TARGET_FILE}

                sed -i "s|image:.*|image: $ECR_REPO:${BUILD_NUMBER}|" ${TARGET_FILE}
                
                git config user.email "yaswanth.padakandla@gmail.com"
                git config user.name "Vercetti06"

                git add Sample-app-dev/kubernetes-manifests/app/app-deployment.yml
                git commit -m "Update image tracking to build ${BUILD_NUMBER}"

                git remote set-url origin https://$GIT_USER:$GIT_TOKEN@github.com/Vercetti06/Sample-Leave-API.git
                git push origin HEAD:main
            '''
        }
    }
}
    }
        
    post {
        always {
            //sh "docker rmi ${REGISTRY_USER}/${IMAGE_NAME}:${BUILD_NUMBER} || true"
            sh "docker rmi $ECR_REPO:${BUILD_NUMBER} || true"
        }
        success {
            echo 'Full pipeline passed successfully! Code scanned, image pushed, and manifest updated inline.'
        }
        failure {
            echo 'Pipeline deployment process broken.'
        }
    }
}
